version: '3'
services:
  web:
    container_name: tomcat
    build: ./tomcat/
    restart: always
    ports:
     - "8081:8080"
    links:
     - dbserver
  dbserver:
    build: ./mysql/
    container_name: mysql
    restart: always
    ports:
     - "3306:3306"
