version: '3'
services:
  web:
    container_name: tomcat
    build: .
    restart: always
    ports:
     - "8081:8080"
    links:
     - dbserver
  dbserver:
    image: tamileng/login_mysql:1.0
    container_name: mysql
    restart: always
    ports:
     - "3306:3306"
