version: '3'
services:
  web:
    container_name: tomcat
    build: ./Dockerfile_tomcat
    restart: always
    ports:
     - "8081:8080"
    links:
     - dbserver
  dbserver:
    build: ./Dockerfile_mysql
    container_name: mysql
    restart: always
    ports:
     - "3306:3306"
